export const auth = {};
export const db = {};
export const getAuth = jest.fn(() => ({}));
export const getFirestore = jest.fn(() => ({}));
export const initializeApp = jest.fn(() => ({}));
export const signInWithEmailAndPassword = jest.fn();
export const createUserWithEmailAndPassword = jest.fn();
export const signOut = jest.fn();
export const onAuthStateChanged = jest.fn();
export const updateProfile = jest.fn();
export const doc = jest.fn();
export const setDoc = jest.fn();
export const getDoc = jest.fn();